### PR TITLE
Fixed issue with SetClientName (CS:GO)

### PR DESCRIPTION
**Pull request by AgentWesker**
CS:GO will not change the name if the string starts with the same characters

Example: 
cs.money MyNameHere -> changes to -> MyNameHere
but not
MyNameHere cs.money -> stays as -> MyNameHere cs.money

Workaround is to set it to a tab character (impossible to use normally) and change name on the next frame.

### CODE REVIEW

**Comment by Totenfluch** [comment]
That is not a csgo problem as your second example worked flawlessly with my old code.
I've tested this for hours and with a large dataset.

**Comment by AgentWesker** [comment]
Removed the code and tested again, it displays the correct name in tab menu but in chat the link will not get deleted without the additional code.

Example: 
Join server as -> test cs.money
name is immediately changed to -> test
change my name to test cs.money 2
name is changed in tab but chat shows -> test cs.money 2

**Comment by Totenfluch** [comment]
it doesn't remove chat links because there's 0 code for that in the script^^
The say hook prevents the name change message from popping up

are you using some chat processor?

**Comment by AgentWesker** [comment]
SetClientName() does reflect name changes in chat though? In my tests just now it correctly displayed the edited name in tab menu and when the client uses the "say" command (with the additional code)

**Comment by Totenfluch** [comment]
ah now I get it.
That also worked in my initial testing - I've spend 2h with 4 other people testing the original script
and we never encountered the bugs you mentioned.
I will do some testing tomorrow as my testers are not here anymore

**Comment by Totenfluch** [comment]
Changes look reasonable, explanation in the AM Thread also looks reasonable.
Overall nice work - well done ~ Merged!

**Pull request merged**
