### PR TITLE
Simple Whitelist Addition with flag support.

### PR DESCRIPTION
**Pull request by MitchDizzle**
I haven't tested this really, please don't merge yet.

### CODE REVIEW

**Comment by Totenfluch** [comment]
someone is afraid of my skills to merge within minutes :p

**Comment by MitchDizzle** [comment]
I've added a fix for the current issue #10

**Comment by Totenfluch** [comment]
As soon as you confirm it is working properly I'll merge it in. Just leave a comment

**Comment by MitchDizzle** [comment]
Tested:
* Without admin flags:
  * Nonwhitelisted url
  * Whitelisted url (no flag)
  * Whitelisted url (a flag)
* With admin:
  * Whitelisted url (a flag)

Seems to be working as intended, couldn't test too much since steam blocks frequent name changes. :+1:

**Comment by Totenfluch** [comment]
Thanks for your work !

**Pull request merged**
