### PR TITLE
Update to Regex & some fix

### PR DESCRIPTION
**Pull request by AgentWesker**
- Updated regex string with optional http / www catch (was requested by my community)
- Removed the player_spawn hook and moved code to OnClientPostAdminCheck (optimization?)
- Moved regex checking into its own function
- Loop through name based on # of substrings found in the match
- Use the "newname" attribute from player_changename event instead of client
- Return Plugin_Continue inside onPlayerNameChange if no regex match is found

### CODE REVIEW

**Comment by MitchDizzle** [comment]
You shouldn't close the Regex handle unless you want errors to occur. If you close it within OnMapEnd then you should recreate the regex within OnMapStart.
Also new syntax INVALID_HANDLE is incorrect, it will be 'null'.

**Comment by Totenfluch** [comment]
Yup what mitch said has pretty serious consequences. Other than that I'd replace the error with this
https://github.com/Totenfluch/SmartLinkRemover/pull/1/commits/86e57b3b45590ab3e05b6dcb1b7c3d60edc1bcd1#diff-e2abc52085f684f54126839d624129d6R50
or I can do it after the merge.

if you implement his feedback i'll merge it tomorrow

**Comment by AgentWesker** [comment]
I removed the CloseHandle() as I thought OnPluginStart() was run once every map and may cause some sort of memory leak. According to this https://forums.alliedmods.net/showpost.php?p=579622&postcount=9 it's only once so it should be fine.

**Comment by Totenfluch** [comment]
Thanks. Merged and closed. Will do some testing tomorrow before I update the thread

cheers!

**Pull request merged**
