### PR TITLE
Update Regex String

### PR DESCRIPTION
**Pull request by Timocop**
Update regex string for better detection.
`([-a-zA-Z0-9]*(([.])([a-zA-Z]){2,5}))`
to
`([-\w\d]*((\W\bdot\b\W|.)\b([\w]){2,5})\b)`

sllauncher_2017-04-01_22-20-37

### CODE REVIEW

**Comment by Totenfluch** [comment]
Thanks for your input!
But it is a bit flawed

Here are some examples:
http://i.imgur.com/vYIxC2M.png

My full testing list:
https://pastebin.com/8cGgSYCa

The aim of this plugin is to only remove the link from the Player name

**Comment by Timocop** [comment]
Oh wow thats alot of names. I didnt realy tested in depth, wops. 
Could be hard to detect malformed domains (e.g domain/./com or domain_com) with regex alone with minimal false positives.
Maybe something like `([-\w\d]*[\W_]+(?<!\s)(com|net|org|de|xxx))` to get a safe starting point could help.

**Comment by Totenfluch** [comment]
That solution looks better than mine but in my detection tests finds less
My pool is based of all people that ever joined my server with advertisement in their names
if you make the last part with the domain ending generic I will merge it

**Comment by Totenfluch** [comment]
Thanks for your changes but I see more problems with this than it helps at the moment

pL0x|google.com
luca???google.com
Lauris/google.com
.Krimz - google.com

all result in false positives (100% match) and would make the name empty
There would be a need to make a difference between obfuscating a link and matching name@link.xxx

Also: wouldn't (\w){2,6} be better than listing all the domain endings in terms of performance?

kind regards

**Comment by Totenfluch** [comment]
Thanks for your work!
But #2 was matching perfectly

**Pull request closed without merging**
